### ISSUE TITLE
Mark PHP 8 as supported

### ISSUE THREAD

**Issue by samdark** [Roave/infection-static-analysis-plugin#101]
I've tried the plugin with PHP 8 on many Yii 3 packages and it works well (same as with PHP 7.4). The only thing missing is Composer constraint to be changed to `"php": "^7.4|^8.0"`. Would you accept a pull request?

**Comment by asgrim** [comment]
I'd say `~7.4.7|~8.0` would be better, since `^` is only applicable to semver, but yeah if we've got CI working and compatible that's a good start! :)

**Comment by Ocramius** [comment]
`~8.0.0` specifically
