### ISSUE TITLE
Make psalm configuration location configurable

### ISSUE THREAD

**Issue by WyriHaximus** [Roave/infection-static-analysis-plugin#28]
> Potentially feasible to make it properly lazy via some more reflection nightmares...

To add to that nightmare, the next step would be to make it possible to also pass the psalm config location

_Originally posted by @WyriHaximus in https://github.com/Roave/infection-static-analysis-plugin/issues/27#issuecomment-702707702_

**Comment by azjezz** [comment]
fixed in #248
