### ISSUE TITLE
Incompatibility with the Composer bin plugin

### ISSUE THREAD

**Issue by someniatko** [Roave/infection-static-analysis-plugin#437]
Follow-up after investigation in https://github.com/Ocramius/PackageVersions/issues/220, https://github.com/bamarni/composer-bin-plugin/issues/138, https://github.com/bamarni/composer-bin-plugin/pull/141

The culprit is actually this chunk of code: https://github.com/Roave/infection-static-analysis-plugin/blob/1.22.x/bin/roave-infection-static-analysis-plugin#L31-L52

It's "too smart" and takes into account the Composer autoload file relative to the CWD, therefore it breaks the behavior if the lib was installed using the Composer bin plugin, which provides its own autoloader in the `vendor-bin/<bin name>/vendor/autoload.php`, which the binary will swallow just fine when using `require __DIR__ . '/../../../vendor/autoload.php` or something like that.

**Comment by someniatko** [comment]
Perhaps the fix may look like:

```diff
-        $projectDirectoryCandidates = [
-            'current-working-directory'        => getcwd(),
-            'installed-as-composer-dependency' => __DIR__ . '/../../..',
-            'installed-as-project'             => __DIR__ . '/..',
-        ];
+        $projectDirectoryCandidates = [
+            'installed-as-composer-dependency' => __DIR__ . '/../../..',
+            'installed-as-project'             => __DIR__ . '/..',
+            'current-working-directory'        => getcwd(),
+        ];
```

**Comment by Ocramius** [comment]
This is a clear "won't fix" for me.

Plugins that change semantics around binaries are out of scope.

Put this in your `require-dev`, since it shares the same address space as your SUT during test execution: it is **not** an external binary.

**Comment by someniatko** [comment]
> it is not an external binary

I disagree with this claim: Psalm is available as standalone PHAR, Infection is available standalone as well, why a combiner of the two is an exception?

> Put this in your require-dev

This package requires Infection, which alone has a lot of dependencies (more than 10), which I don't won't to influence my project's. I've already had a real problem with some testing utility, that's why I switched over to Composer Bin, and so far this lib is the first I've had problems with.

> a clear "won't fix" for me.

I understand you want to draw the boundary of what you consider a bug or an issue worth attention, and what not, but I am not sure relying on CWD is a good idea anyway.

**Comment by Ocramius** [comment]
Psalm, PHPCS and PHPStan **don't** share the address space of your SUT: this does.
