### ISSUE TITLE
Release supporting Infection 0.26.15

### ISSUE THREAD

**Issue by pamil** [Roave/infection-static-analysis-plugin#449]
It seems the `composer.json` has been updated to allow for it, but it's not tagged, is there anything blocking it that I could help with? This would let me use `--threads=max` 🎉

**Comment by Ocramius** [comment]
Cutting a release now :)

**Comment by Ocramius** [comment]
https://github.com/Roave/infection-static-analysis-plugin/actions/runs/3273211827

https://github.com/Roave/infection-static-analysis-plugin/releases/tag/1.24.0

**Comment by pamil** [comment]
Thanks a lot, have a nice day!
