### ISSUE TITLE
Dependabot flood

### ISSUE THREAD

**Issue by someniatko** [Roave/infection-static-analysis-plugin#45]
I really like the idea of this project and therefore I decided to watch it. However, I was quickly forced to regret my decision, due to constant dependabot PRs spamming. Maybe it would make sense to somehow configure the bot to make such PRs updating all at once and daily, for example?

This does not really issue of the project itself, but anyway, WDYT?

**Comment by Ocramius** [comment]
> Maybe it would make sense to somehow configure the bot to make such PRs updating all at once and daily, for example?

If feasible, most certainly.

I don't mind the flood of updates, especially since the tool is pinned to patch versions due to it using non-public API (therefore, integration tests and precise version pinning are strictly required).
