### ISSUE TITLE
Add `vimeo/psalm` version 5 support

### ISSUE THREAD

**Issue by vjik** [Roave/infection-static-analysis-plugin#460]

**Comment by vjik** [comment]
@Ocramius Why closed issue?

**Comment by Ocramius** [comment]
Because it was released 1h ago, and it will be picked up by automation.

There is **NO NEED** to report issues for dependency upgrades **ONE HOUR** after the release, and in fact, it's plain bad netiquette.

**Comment by Ocramius** [comment]
FWIW: https://github.com/Roave/infection-static-analysis-plugin/releases/tag/1.26.0

**Comment by vjik** [comment]
Thank you! But can you keep support PHP 8.0?

**Comment by Ocramius** [comment]
No, PHP 8.0 is gone.

You'll have to run infection from PHP 8.1 or newer, if you want it with Psalm v5.
