### ISSUE TITLE
Release for infection v0.27

### ISSUE THREAD

**Issue by simPod** [Roave/infection-static-analysis-plugin#475]
Hello, can we have a new release? It's currently blocking upgrade to infection v0.27. Thanks!

**Comment by Ocramius** [comment]
Haven't gotten a dependency upgrade patch yet? 🤔

**Comment by simPod** [comment]
I inspected commits earlier and spotted this one https://github.com/Roave/infection-static-analysis-plugin/commit/b3486364bce3bb0e81ed988e9533fb726571eb17 so should be fine?

**Comment by Ocramius** [comment]
Thanks, that suffices 👍

**Comment by Ocramius** [comment]
Ah, weird, it started updating without making a PR 🤔

**Comment by simPod** [comment]
Great, thanks
