### ISSUE TITLE
Update to infection 0.20

### ISSUE THREAD

**Issue by WyriHaximus** [Roave/infection-static-analysis-plugin#79]
A new version of infection is out: https://infection.github.io/2020/11/01/whats-new-in-0.20.0/

**Comment by maks-rafalko** [comment]
I will use the opportunity to remind that we have a ready to review PR that adds support for plugins, specifically created for this Psalm integration: https://github.com/infection/infection/pull/1327

Ultimately, it will allow to use Psalm with Infection without the need of such issues to upgrade to the latest Infection versions.

**Comment by Ocramius** [comment]
My bad for not having had any proper time for OSS over the last couple months, sorry 😞

**Comment by Ocramius** [comment]
BTW, send a patch whenever - don't have a PC with PHP at hand

**Comment by WyriHaximus** [comment]
> BTW, send a patch whenever - don't have a PC with PHP at hand

If someone doesn't probably looking at doing it tonight

**Comment by WyriHaximus** [comment]
Seems Dependabot beat me to it: https://github.com/Roave/infection-static-analysis-plugin/pull/86

**Comment by Ocramius** [comment]
Excellent: releasing now.
